#!/usr/bin/env bash

set -e
dir="$(cd "$(dirname "$0")" && pwd)"
script="${dir}/../dist/ColorEcho.bash"
. "${script}"

awk '/^function +echo/ {print $2}' "${script}" | sed 's/()//g' | while IFS= read -r x; do
  ${x} "${x}"
done
