#!/usr/bin/env ksh

set -e
dir="$(cd "$(dirname "${0}")" && pwd)"
script="${dir}/../dist/ColorEcho.ksh"
. "${script}"

awk '/^function +echo/ {print $2}' "${script}" | while IFS= read -r x
do
    $x "$x"
done
