#!/usr/bin/env sh

set -e
dir="$(cd "$(dirname "$0")" && pwd)"
script="${dir}/../dist/ColorEcho.sh"
. "${script}"

grep -E "echo[a-zA-Z]+()" "${script}" | sed -e 's/()//g' -e 's/ {$//g' | while IFS= read -r x; do
  ${x} "${x}"
done
